<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!-- 添加 WinForms 支持，仅仅为了拿一下屏幕宽度 -->
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>NPS_NotchPeninsula-Icon-512x-NEW.ico</ApplicationIcon>

	<Version>1.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="NPS_NotchPeninsula-Icon-512x-NEW.ico" />
		<Content Include="data\image\bilibili-logo.png" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\qq-icon.svg" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\wintoast-icon.svg" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SkiaSharp" Version="2.88.8" />
		<PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.8" />
		<PackageReference Include="Svg.Skia" Version="2.0.0" />
		<!-- 新增音频采集库 -->
		<PackageReference Include="NAudio.Core" Version="2.2.1" />
		<PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
	</ItemGroup>

</Project>