<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<!-- 已经为你升级到 .NET 10 -->
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!-- 添加 WinForms 支持，仅仅为了拿一下屏幕宽度 -->
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SkiaSharp" Version="2.88.8" />
		<PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.8" />
	</ItemGroup>

</Project>